apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
  labels:
    name: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://gitlab.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra-tools/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true