apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    name: sealed-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-rtc-demo
  namespace: argocd
  labels:
    name: web-rtc-demo
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/web-rtc-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-resources
  namespace: argocd
  labels:
    name: common-resources
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/common
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda-platform
  namespace: argocd
  labels:
    name: camunda-platform
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/camunda-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
  labels:
    name: elastic-operator
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/elastic-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  labels:
    name: elastic
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/elastic
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    name: postgres
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  labels:
    name: reflector
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/reflector
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgrest
  namespace: argocd
  labels:
    name: postgrest
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/postgrest
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: argocd
  labels:
    name: kube-prom
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ktor-camunda-worker
  namespace: argocd
  labels:
    name: ktor-camunda-worker
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/ktor-camunda-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    name: redis
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    name: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  labels:
    name: rabbitmq
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  labels:
    name: istio
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
