apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-argocd-server
spec:
  template:
    spec:
      containers:
        - command:
            - argocd-server
            - --insecure
            - --staticassets
            - /shared/app
            - --repo-server
            - argo-cd-argocd-repo-server:8081
            - --dex-server
            - http://argo-cd-argocd-dex-server:5556
            - --logformat
            - text
            - --loglevel
            - info
            - --redis
            - argo-cd-argocd-redis:6379
          name: server
