apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic

helmCharts:
  - name: elasticsearch
    repo:  https://helm.elastic.co
    version: 8.5.1
    valuesFile: values.yaml
    releaseName: elastic
    namespace: elastic
    includeCRDs: true
