replicas: 1
resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 500m
persistence:
  enabled: false
antiAffinity: soft
ingress:
  enabled: true
  className: "nginx"
  pathType: ImplementationSpecific
  hosts:
    - host: home-server
      paths:
        - path: /elasticsearch
