replicas: 1
resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 500m
persistence:
  enabled: false
antiAffinity: soft
createCert: false
extraEnvs:
  - name: discovery.type
    value: single-node
  - name: xpack.security.enabled
    value: false
