---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:43.232.0@sha256:aa3af52641f0713f9f00afac463cc3bfb2aa31c590fed9b04ef10b8821929a2b
              envFrom:
                - configMapRef:
                    name: renovate-variables
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
