---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "antoinecampbell/kubernetes-manifests",
        "antoinecampbell/home-media-server"
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-variables
data:
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_ENDPOINT: 'https://api.github.com'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  RENOVATE_CONFIG_FILE: '/opt/renovate/config.json'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgDMrsODMENXh4nbACc6aQAVX0iDBWBw5HlrguyDHEhPVTFsWqoIDnFKLi51gZsUB/0/rKD9EM4FsPe1aKCeOiUIZUlxus45+xFcw0ki9pE5h7DWnb6PEpbYDsEpjhd1k5ejmrfZNCgRJM5eCCXR6gTvp/ct7y9ob4FqxKM36QgIZbIrCX9yO2qcrrjMQUEzMxELWGlzt3nnrFj3oznrempTEweb/TDv1fI31wsGLogRqb17EW6fKyYhoUhNCZ7hX3gg6qHoNVdqGXGYeFDBMCzXf5GxU5z1nDD0RkmiJDx29v9b0no68/XCAyzgcLK/3DBQq102EIgOweIOoLZjh76ZpdbdpII+JJKpaxfJs3o/GNuhNkqVuzcOAYCF0dTr0tarqxCBL7LW8APXY3jADDE0/gfP2d6smHrFf0pClfg+SyC2WMB3l8Ddd+GWWNkbLXpKnwqiVKR7olfgyR/A4xI3Gq/w7Z8QYsQ241R0BE4dk010e9PF8WYVaXy54IP/yO+IfFhQe2CpalTPn1TIDhQqBkhiIsaEZKG0npR9AuBDJ/JNarZNoPIv34rgHgPh15ia1oMEI0d+sX1fPav8Q4y9HvoJu8f4/UDp8Y+aYp7sHWoylp/acTBWb1786J7xCqFVrrl+wo8kv2dI8uem91/6V3rEa80sVD6clwrQuoZ3O4rz5/1d8DIQjo+bcnQ5L8xYYvAaztKL9r1asoqLxvkGtulkEzDizJm9KlXtZ5te3fD1ym3I6slj
  template:
    metadata:
      name: renovate-env
      namespace: renovate
