---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "antoinecampbell/kubernetes-manifests",
        "antoinecampbell/home-media-server",
        "antoinecampbell/operaton-testing",
        "antoinecampbell/ktor-api",
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-variables
data:
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_ENDPOINT: 'https://api.github.com'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  RENOVATE_CONFIG_FILE: '/opt/renovate/config.json'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgA1uMZAOL8fBQbVo1Y8wJMY1doFR0pmpEBysvuxcTb1HV9J9N5A6RyDDsGV/Jy2VPeT+DECoXb2t0C/mCndu586IcqTBkjtEhx3mn8X5hl2314kP4ZSt4BaG8bLZbDHpwKbQgT671ncKxlCdSiOqKRTb60DtF6Dypn5UGQ1Ui/OeFg9asZjS+88aw4WLMxztfQ3oHY2vspygddKlKklTWUCdbdAtZgzL9/0OaUew5UgUlUnLNDrvgNunYhO9UUt8ppjSFuCUcoAWVnIQwzJZQn4y8lo7n34vIiTq8xJolOj8fuvFht3opt6I/aWRQqi/jZA1LWWSfcJxThzsui0B1fko8WfAmrK7Vs3Pp5PY17mXXMX2ps8eMxrnXVegMj99xaXCVRSP3aeKC2I9vnb0LwjU/xh8bkflJaqKJZQT33i/QuhTO2FEtiVx1d5vux8BlOD1HA1E9dsRwW9xwEeGmtmkB6Tvk92VgU4QkM42RcoxVx9sc1vBzAyivAdbsXE3O4FGlyFsB/UO5BpidfBF2E1iG5PlTTL6h038UccfVyva+iLCx0lCx4zJgLIRzpHu1vpgnTg8VQ4D4SDpQCpfAClQI60f+gsoQMxzjcdOIeD+HWo67FVsnt4H9IS3UwaxL4nDyGmBTetsHnLxxSk9Xuw+bp5vfCXNwbM59oFqp9eWpxc6WHdw/pwxDPz35qmSaZklUoYtCXoQ4Q0athxboMHM9F0UHPnqFqgM8BCoBv9kU6nUTX3BLX9
  template:
    metadata:
      name: renovate-env
      namespace: renovate
