---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": [
        "antoinecampbell/kubernetes-manifests",
        "antoinecampbell/home-media-server",
        "antoinecampbell/operaton-testing"
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-variables
data:
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_ENDPOINT: 'https://api.github.com'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  RENOVATE_CONFIG_FILE: '/opt/renovate/config.json'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAne2HQO3mp0BfZerDLcPR5fOGEAqNEuVLzLnXkrboHPQrcPWKQlbEG42OjzheAy6T+pVNW/E9cXFs3+ut2XqbQHW2h/DRYTUYGpQ6YjD7VohkmBJdZsPAeluIbJ0r+cTIRWLKwIdBe0sDV7kwXMZN2vOP9S2sRyYrKRKcnl2AaUOevprShkyJZJecJjccPtF+ytpJ59qSPFMRi3qFXUO1rtAhSiSvUd0yh6QHzNhGXpkZeM+cWlZ4ws3NH2Qa21t5QsaZxVUEzw/ygLgH8aYnfDr7XRmARIf6/ewpH/ketGmfj/j391PSlI9CBVIgIVQtGuDpZFO7h1d/Sg0dSSPjPIp73K6wf1lYnvYpuKSQpqoWHrPqocf+kvnPCz3y3oWftgOZlWifciYzEZ+ELBaQFJLDe+4h2mjxOFbMu+RP5Zc0oqgGUoloD9Yx7sGdZe/q51RnVIruh9B9qiopd9nAM7kODVSBSI/KF98zolPblXUTnjRVZBJuj5j4sYPqeQeKtfyCF+pTdvmQcYJfQH7GiRRNnJunN+NehIC7iWNTyt6NPXmcMuYFDHk/Uu1PiloE5DWhyIv5IXdZ3u7nT7w1lN4gkOIDvHbQ2dXquqpvbJCgkhZSQtclwgZItRKMQ+b5g1SbV9fucsRACCjwHIBffqeLwGYGNBqhQ8VJMmV+BRnfH4HABMcjNKU99L8z/xh7MrcIG7c97ar+qxe28iHyawk2Ss6W473kLvkwKMYN4TH4xA5tpxJ7z
  template:
    metadata:
      name: renovate-env
      namespace: renovate
