apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 18.8.5
    valuesFile: values.yaml
    releaseName: main
    namespace: postgres
    includeCRDs: true

resources:
  - secret.yaml
