---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgCM+AwFmVP69oMAr79KGysIOuMNdjiEiAq2HIQ0syH58Xe27Li7lxq45ct8HocmBQgep9fUWCQ8HS92MPEeebYR13u1zbTkGKTfrfVNzp/oiIQWjNRFms2qfkhMt/qYX0ww3Rkbsqh2aJ8xHu4XDjmO8f4SBMBRc8BlqYzHoI7YdnTpuvL9agFWKfzMVDnD/+9JxKDAFwvl+/OntJzBDgDm6i6C51KKjBTMkiATicx4dtd+nD7zsvpEPkXVJmPrxEn4qc26yjnRH0Wyc5RT1G3Pjb0ln+C53MH9qUF6LmX6Um/bQRHLYufN89zR1eAX86FHe8vQ1toTR+IlW/jgXQTIvPTM+JNlyp9iNBQK48fcc6Ed7SGalvKWHbkkufSWcKvEhQC3kq3NyxoZk8/Z4Sk+C4lCL939xPaVR83tDgUEJMslgYGFEwBYSlSMY5qILSSIJRlWZHbscXXQGVyegtwUAJUf4BqWmek0iZKdn8Ok9dCqaioSiJOoMQ2k2/hfS+aIFB92sSgGZBfvARcg4G4Je5+XzGI4Yg8wyg+0yJuyk9MTHLhach252uHcobB9emzJyQBU71fphTH7k+Lgq6drvhLW47Zmmngoj/jdasOEpS+0ZqF5HGG2hIstghukiqOPUXTHjICMBEbAUyC+3m4hi8yGvjNIYN4E2c0G8fN8HIjAc4EIozgMtjUNhB/PbbRgwncUACSKIw==
  template:
    metadata:
      name: postgres-secrets
      namespace: postgres
