# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/alloy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/argocd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/cert-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/k8s/base-infra/cloudflare"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/elastic-operator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/ingress-nginx"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/istio"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/loki"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/monitoring"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/relfector"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/k8s/base-infra/sealed-secrets"
    schedule:
      interval: "weekly"
