apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic

helmCharts:
  - name: eck-operator
    repo:  https://helm.elastic.co
    version: 2.11.0
    valuesFile: values.yaml
    releaseName: elastic-operator
    namespace: elastic
    includeCRDs: true
