apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.2.3
    valuesFile: values.yaml
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
