controller:
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  service:
    external:
      enabled: false
  hostPort:
    enabled: true
tcp:
  5432: "postgres/main-postgresql:5432"
  26500: "postgres/main-postgresql:5432"
