controller:
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  service:
    external:
      enabled: false
  hostPort:
    enabled: true
  updateStrategy:
    type: Recreate
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
revisionHistoryLimit: 0
