controller:
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  service:
    external:
      enabled: false
  hostPort:
    enabled: true
  updateStrategy:
    type: Recreate
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
tcp:
  5432: "postgres/main-postgresql:5432"
#  26500: "camunda-platform/camunda-platform-zeebe-gateway:26500"
