apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra-tools/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    name: sealed-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-rtc-demo
  namespace: argocd
  labels:
    name: web-rtc-demo
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/web-rtc-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-resources
  namespace: argocd
  labels:
    name: common-resources
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/common
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: knative
#  namespace: argocd
#  labels:
#    name: knative
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
#    targetRevision: HEAD
#    path: k8s/base-infra-tools/knative
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: default
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
#      - PruneLast=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda-platform
  namespace: argocd
  labels:
    name: camunda-platform
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/apps/camunda-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: elasticsearch
#  namespace: argocd
#  labels:
#    name: elasticsearch
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
#    targetRevision: HEAD
#    path: k8s/base-infra-tools/elasticsearch
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: elastic
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
#      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: monitoring
  labels:
    name: loki
spec:
  project: default
  source:
    repoURL: https://github.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra-tools/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true
