apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  project: default
  source:
    repoURL: https://gitlab.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra-tools/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true