---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: elasticsearch-main
spec:
  rules:
    - host: home-server
      http:
        paths:
          - backend:
              service:
                name: main-es-default
                port:
                  name: http
            path: /elasticsearch(/|$)(.*)
            pathType: Prefix
