---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  count: 1
  elasticsearchRef:
    name: main
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.12.2
