apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    repo:  https://charts.bitnami.com/bitnami
    version: 1.1.2
    valuesFile: values.yaml
    releaseName: sealed-secrets
    namespace: sealed-secrets
    includeCRDs: true