---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-infra-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            path: k8s/base-infra/cert-manager
          - name: sealed-secrets
            namespace: sealed-secrets
            path: k8s/base-infra/sealed-secrets
          - name: reflector
            namespace: reflector
            path: k8s/base-infra/reflector
          - name: ingress-nginx
            namespace: ingress-nginx
            path: k8s/base-infra/ingress-nginx
          - name: kube-prom
            namespace: monitoring
            path: k8s/base-infra/monitoring
          - name: argocd
            namespace: argocd
            path: k8s/base-infra/argocd
          - name: cloudflare
            namespace: cloudflare
            path: k8s/base-infra/cloudflare
          - name: loki
            namespace: monitoring
            path: k8s/base-infra/loki
          - name: alloy
            namespace: monitoring
            path: k8s/base-infra/alloy
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:antoinecampbell/kubernetes-manifests.git
        targetRevision: HEAD
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
          - name: web-rtc-demo
            namespace: default
            path: k8s/apps/web-rtc-demo
          - name: common-resources
            namespace: default
            path: k8s/common
          - name: homarr
            namespace: homarr
            path: k8s/apps/homarr
          - name: renovate
            namespace: renovate
            path: k8s/apps/renovate
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:antoinecampbell/kubernetes-manifests.git
        targetRevision: HEAD
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:antoinecampbell/home-media-server.git
    targetRevision: HEAD
    path: k8s/argo-application-sets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  labels:
    name: istio
spec:
  project: default
  source:
    repoURL: git@github.com:antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
