apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: sealed-secrets
    repo:  https://bitnami-labs.github.io/sealed-secrets
    version: 2.6.0
    valuesFile: values.yaml
    releaseName: sealed-secrets
    namespace: sealed-secrets
    includeCRDs: true