apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - issuer-staging.yaml
  - issuer-prod.yaml

helmCharts:
  - name: cert-manager
    repo:  https://charts.bitnami.com/bitnami
    version: 0.8.2
    valuesFile: values.yaml
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true