apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo:  https://bitnami-labs.github.io/cert-manager
    version: 2.6.0
    valuesFile: values.yaml
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true