---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-create
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-create-python-app
subjects:
  - kind: ServiceAccount
    name: python-app
    apiGroup: ""
roleRef:
  kind: Role
  name: job-create
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - name: http
      port: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: local/python-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
      serviceAccountName: python-app
