apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: main-rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = admin
  affinity: { }
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: rabbitmq.home-server.antoine-campbell.com
      http:
        paths:
          - backend:
              service:
                name: main-rabbitmq
                port:
                  name: management
            pathType: ImplementationSpecific
            path: /
