apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.21.0
    valuesFile: values-base.yaml
    releaseName: istio
    namespace: istio-system
    includeCRDs: true
