defaults:
  ownerName: istiod
  pilot:
    autoscaleEnabled: false
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
