apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: cluster-tools
  source:
    repoURL: https://gitlab.com/antoinecampbell/kubernetes-manifests.git
    targetRevision: HEAD
    path: k8s/base-infra/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true