apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: antoine@antoine-campbell.com
    privateKeySecretRef:
      name: letsencrypt-dns-staging
    solvers:
      - selector:
          dnsNames:
            - "home-server.antoine-campbell.com"
            - "*.home-server.antoine-campbell.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-key
