apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

configMapGenerator:
  - name: cert-manager-grafana-dashboard
    files:
      - grafana-dashboards/cert-manager.json
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      labels:
        grafana_dashboard: "1"

resources:
  - issuer-dns-prod.yaml
  - issuer-dns-staging.yaml
  - issuer-self-signed.yaml
  - secrets.yaml

helmCharts:
  - name: cert-manager
    repo:  oci://quay.io/jetstack/charts
    version: v1.20.3
    valuesFile: values.yaml
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
