apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

configMapGenerator:
  - name: cert-manager-grafana-dashboard
    files:
      - grafana-dashboards/cert-manager.json
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      labels:
        grafana_dashboard: "1"

resources:
  - issuer-self-signed.yaml
  - issuer-staging.yaml
  - issuer-prod.yaml

helmCharts:
  - name: cert-manager
    repo:  https://charts.bitnami.com/bitnami
    version: 0.8.2
    valuesFile: values.yaml
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
