---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
spec:
  encryptedData:
    api-key: AgCpwZg+Nij5IBrqJYFopJWcqc37IqfnAW8V1KhgZMi9n7vPAUeVCymbURlZKL+Bdq2lKAVohNJBxsptSSYZX3YeHHHObbmpmDii0GrlNde89DuqnmE8NcHT7ADJ9BNJgsvQ2AXP8q1SsaCpreosoqmLnrk0vOQeL6GJwF+eQz98QKfT7YmDncROf67dNtZjK5C0E/lEyRnoHprKK6Gy0W5Ibcmi3wc6inBRZ23fMYUFFjcDn3CsQff3YdOpl75NFub+gY9+VdZewad022veKB17uHYVnzWEGjeF2KoCc3X1AeiIVxobI0hHXflxp08wvjZ0HO8ZBjD+VZCfB+2hLwYY92tOYW2vCPAPlI8OpwOGw4jktQcr5CDuf0/ywVFG3/X71gC+M/+rfJH9isxIjB7UrWKsTdhPHWGyVl5RZdfbk9AdVkbnottZWzVTGB0gtwLm7ldO/NWuy25/0CRPwRIUfMOhvTfZyMAWM0LTeJ41mAa7NFEAByro7SpwxQboBe4W3EOf5eqyq2LEArP5r4SfZq/xhMInlgP9iYTC6ZLn2b9+ZRbK/jU/a9Nek1LpJs95GNnzsvsVAJR3F0ZZJEBdsBpYzWdT0oOxt51sHYh4Pqjxfd4vlDajHfA8GJUru/UKuMtGMQJjxBg/+LaaJY+C4fQzRYUycvgmjDrvHzCquIBPKnPeYlgtY2iJGnOuQAku9THmeAARUXxSUood0eFS3x/Pc4wMoG7/DIqWr9UQleQp50k6F49PZ6MC2U//TMUxL+afiQ==
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: cert-manager
