apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana-community/helm-charts
    version: 6.55.0
    releaseName: loki
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
