---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
spec:
  encryptedData:
    admin-password: AgCF3lKZJC19q1r+Ucej5Vf2u7ggsvsmRMB4ZwwnrjifEwNkKcKd7V5TI6PTdLyP2uiZPODUepab4f8+AqXeas7+AB3q9qQ/tqgy8ulYNIm4sNjvKN9qR7zKt/rCq/RkLm35cYI0F44c91qFY8Wj7WglF42EYEgXEO3wqnWI3l2B/yx7x0V2q3uz/wbyn5ARj6MHpteac/nlAxEGyckCEM67eVlsDPxeClDHLuemToqKn7YKF723MaZhh9ZUCoCa8a/LhrBlDNRSCRqFLARB/1TTdpjbfLQ16ca5LXm1czsfh22rFME01fPtzOP+FSDQ5kboD+GucJxcDnl878A+SwBnTTfp4Yrhoh1Km1QxCW1z4zpMvmHqVWQDSllRMfaP4gdXx+hINGkldCH/t6vPkc/LdZHzfoU9LHnYQTG7staI3qGW5YQXynolbe6oqmBn47G7mo9FrJhjxT2m/dCcad8yvntSP0e0ojvmdRyqtJvcnY97iik29vhVJp94j+pIx7ZIQS3+3p31Ik37JeolEmj4UpMFZRDDBg8+6q/fnGf2T2uXFcDcHkoLgnGj/GwNYON+0HsWD0LtmTwl3xJ2wZa6wYb3DvncpiTxRlp9NS+YGhOWwqB1LghuCsrTRcV78Npiq2j8Du1Gix0LxHz76RzVrL5fvPWFP7+oLDaYdh9EzaZ3E6aszh7XQGo2GWJUQR6THp8VeuKbE9tElX0q
    admin-user: AgAguMtI3Od0Zhq9ldrVvz/TUtkBPnMT7xhYbVB7VDSULJ6MMN3vmQTNf2voz1U0rl7kZrgJbXj01tMotbdNjy7uP37P62Mmm5CIc+Yetu+30HiORV88QLvq/rTxCwRQgso8h+05bhXjwzLXfiObOoPFkbV+ioY4Mhl38MIfVK21VL+tt8NyiO9XMlxxtBNjGIJKwTs/AaBEv7dQsxZs3j4aETZ7gO+QcD7tfwgeRTwjgR0/eAx4Mzl5zamCNp0KZ2PcpT5Rw5ouD9FpLfGRqT9T2Cil4Uq8DtfSWpcZJSoWIJzlBPay5xOQMmxv5wqEz80gtM+FPZ9O7ZEyA1hBUiBiqtpBhyHf+daGKcYAMc7LjJEd9YIsFF0LLlMCJWJH2YrI7HGf8l0Borz4xeLGGdCthC7bdNl08NgIHyCeRWKz1WJUKlJNjuY9FYC+kAN0JeE2qleSWWmdz/WRTJgiRqyzpJefF4DY0BQfZ4C7oqWL51R1pJKUfUh80x/XF7ga0GUbbTYJprSGL13GMR4vCZxqsBWOks+mkEyDFBeugEbREicycn9F+LT8hGfOQfWjn/KJ1GC47ezWqqpcM+VA4PAYO78vmiy04YEEvrGY9Um2amh6exSYymFj/JHY7UGAKTW6UDQuqNvs0xHwJUsIf/uo+YGrHgnzDBoP9W/rXclEzmih36nl5oEukZsdIYluV1nHBaLL/w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
