---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB4zIvm4Cbnoenndd6cn8LUzo1Lbl1GmTshKMWRoTYkmR2AeJ3i9z7bfPzwmdwGyjBRh7pXup3WWgERCLrpGDZ0d1tR36icUgvgaNrg4G2DBcVoRHxFFly4zSUnNSFMe4LrRAYSa+Ctj2UtZVLP786Ic6sBlgp3Dx831m7rnE1GTeb2B20EzFuENoNpYLrldsGMZhPzozaRS+fnRneDuAxivklccaq6ccT/SiG7cxnTBFf3xnlmKW27EDwkTXwvEofGHLNLICYqAfaDxXB/f4fD4F3vuXtcBcLC7pYU4y+KrImxMKq9EN5bf66GOH0bk9MJvSWY7DDSfMs4jBnJYjTnPsz8Kg4hZrkA09QAbUuVtV3th0quPgXGjASqF3Cvov98iSmgh3nLjBDWUx4yH7YUd5xiRuZE6A4NDYzvdT/PtuA7CPVdDgjsXZbszDCQV1fNk9ybNPvTQXlm/7tRDUafX1wOrdtkiwLMwkY6zhrENOyU+3aDOPVmmai6wma0DkaNnVwu/oSpQBUFHjmCJNPaDiQk7b9VF+K1ktIbgQs/ZD6Xv+XkX9DAmKdsX/q8jbaHGMJcqUBm60KPJzJnnbrKI50bBFGAHOhikRfw1eeS0FyfIEyFj7UFSYOh4+eFUPTF6abB7sHBfw6leb0eCs547hz1hdaMKhXRE/dxOcG4lJi7+BG07I8fMLVIeWuNoPBhkKaAbzkyjnxNzVvxIaZU
    admin-user: AgB2ARc6kLqS5LDZl2S/WNttK0PY8M6C6bG6XeCclF5mfXJY/jTNt3H0cJwuGnnrwkZo2VvWb9yhUPu8EZDgm0Pxoee+n7EEb5v5bQv0D+7d6xmxTNwPIvncwyop2jGmKkUFNades4s6dJMnZaG7HcG26pdwD3yBjr9psyQx8xY5uQtm7cmZHIs0TBsewmiOTuoFRn3vW32QQClHwl4o9Z1tJ6vq03bBrrJpLhfDp2F2y4hk4nGbA1Hon6kRbhgzoyLkoFFAC++eCWYR53sKlxuGgTzAtEoOGL67HfMzikuLHP8ilNdlIcbYAp7PDt+i0xEcJKOu2r2C2Q/q/TzhcgQ/egYy4h373RygBjPSNqoebISLPuFpx4XBQ3puCuaSgZCJtz7ntSensSm9hYzqEI/fZX2pKmKsF8uPHN3sXM+CpSZg3Ds/B2Emx7hy2r34p2+SPgCL0rEO4vxIC6iAMo9TfB5I9yFBtGvxCFnBhtGJlihrA1+Hoeq3HAcsHSJfC8P7GYWxG3jlbTH91GAb9Ev315hotxpdjBklZYCR+dq5+13afAs3MAkF6a6tumdWFW3UJSF81GMVPIbTW4GEkbZ01gpZE3FuDv2hXplQoj4S0EfIQ0hmx+8oaOykzgjjYzXbN405thpW6BUVlpHua63eB1uJt7j3ffvzmV9A5YdN+kPLcAHjJGu0y/VK7ZRlGO/ouH/ruQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
