---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
spec:
  encryptedData:
    admin-password: AgCBLA8TNiN7j39Pzi4om+BZ2PT1Y+Q/e5VhvgCFbaXOK4Bc7CY9wik6NbWoPvodRYxbhzUC+rwv5KGhFaSJzWTofbfrPLWLL4zdYI2+mgzIzSSaPAkCOy3dEXtdFCnjufBVbRemHGv/ReimITQov22T2cYh1AWKAwFGCgJRNWYqZ/eIFWDAkkp/G4A+cAzD/nG9xYdwDcbgT1eWCCF5PRhLE0WyDQVNaNhY+ThvmmgGiArUA3bUfvJhU0/eWQu3tsUiW2+RzlzzsrsqXwZlNPvNZYTh/QTVL3cECywjEe0v1S2YKyw5cQyG7r8VwoBcrAVrOd8KfXbwetT7BLOwRlX230mhKyvfQXDrNox9OHJ1DS/8KALMK4GfhDi+tmBA4nrCzne1hH/DgfJpmLTDsBTxe7w53dWegKZBlU3+ns9rPGtqkSJtYjpRlBLSFOhG+lj2lj2GlmvYWuR9r8VK0Hq5ZvE8aUb5YEb0mCSIk+RuA7gErZDeb0z9QLF5sLJfsMxf53JSJV7+2zWoBrr9rFrK+J/12FcXkdERivcgCkUZHBSfLYQBoBkfkxt/vNTMSQkTBfiMUSWLVhBJgi4pnFCosUVH6Wh/Fk27wFvlzncvIYTPAy8o6PxNs/NYebKQps1+4pBTHkMlH/wwPECoshBUYrj5Jg9NliQ3/RkTniTjDDDmcIw8/npPeF38xwlmY5Oz9HOujw==
    admin-user: AgBQQGXd2RW6qtNjsu3HoUvOUL+kfOU5EB75yWBwPAdDdLcFLN0fpN4Ycp+0drKSIszJq8PLWWwNFj1PHIaMmI+sJIvM7ty1cHhpEIxVDMFjgm0jkidbijlg6fY203IVxNYhRo/bxhKNUAEvZ901dcCKbdoA9oNtZahVneUfvlOp7YYhJLaOfsLRTYoBGY3k7ZCNQKUl29Ho6M6Hy/bhP2NwJ4kd+snbr2uwwv0ghbOfu6T/RMNEO7BlrWIdezBeWqptSYRIezpR9IpzNP+sLk91FP24J4uSwK/jHT6BmWqfMama82XmQzxjShzkpN6Gfi5TLMrw3MCeuX070qrE7Bc1UC9/3jSo0ecxOYgh76JP5O1PGnKge11iVKpukZ24NWUgBlRh4/xYrZkGPk3HijeW7oP1kcNd+TW3XjBCyFNsQa8qbXZxtOaXEWLA40kfaliE08nbNUz+KcunzVMy+Zhu6v6bwy2PJEiJ/aOwlBCyWZaOW/+RTbTo5eo5b9Oqam2W7N5+qIQT7i5HUmnvEm7txPln2gWzcqyyNJhD6lk7yx7wDew8BR5x7nO6jVNdK1eWz7/niLLxDI91OgOV8euOARno++cXtQU/1AWJloizR+E9WTVgojSHRk654FBEXneqe7XNKqtK0jzgYOyVzQDiWgR+vj84Fqr+EHWt4Q1RaJ7gL4FYqGr847Lmn8jhHTS5S3JNWw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
