---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    monitoring/component: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/antoine/home-server/monitoring/grafana
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      monitoring/component: grafana
