prometheus:
  prometheusSpec:
    retention: 7d
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    hosts:
      - prometheus.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard
grafana:
  grafana.ini:
    server:
      domain: grafana.home-server.antoine-campbell.com
  ingress:
    enabled: true
    hosts:
      - grafana.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard
