prometheus:
  prometheusSpec:
    retention: 7d
    routePrefix: /prometheus
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    path: /prometheus
    hosts:
      - home-server
alertmanager:
  alertmanagerSpec:
    routePrefix: /alertmanager
  ingress:
    enabled: true
    path: /alertmanager
    hosts:
      - home-server
grafana:
  sidecar:
    datasources:
      url: http://kube-prom-kube-prometheus-prometheus.monitoring:9090/prometheus/
  grafana.ini:
    server:
      domain: home-server
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    path: /grafana
    hosts:
      - home-server
#kubelet:
#  enabled: false
