fullnameOverride: kube-prom
prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 3GB
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    additionalArgs:
      - name: query.max-concurrency
        value: "4"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          selector:
            matchLabels:
              monitoring/component: prometheus
  ingress:
    enabled: true
    hosts:
      - prometheus.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard-signed-prod
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard-signed-prod
grafana:
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  grafana.ini:
    server:
      domain: grafana.home-server.antoine-campbell.com
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
  ingress:
    enabled: true
    hosts:
      - grafana.home-server.antoine-campbell.com
    tls:
      - secretName: home-server-wildcard-signed-prod
