apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

helmCharts:
  - name: redis
    repo:  https://charts.bitnami.com/bitnami
    version: 19.5.0
    valuesFile: values.yaml
    releaseName: main
    namespace: redis
    includeCRDs: true
