architecture: standalone
auth:
  enabled: false
networkPolicy:
  enabled: true
master:
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePorts:
      redis: 30637
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
