apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.7.13
    valuesFile: values.yaml
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true
