configs:
  secret:
    argocdServerAdminPassword: "$2a$10$3oZjPu9AFz33sKQ3LsQ9UuquA6RttoURjs6CXRCFazevdydHaa0ba"
  cm:
    kustomize.buildOptions: "--enable-helm"
  params:
    server.insecure: true

global:
  domain: argocd.home-server.antoine-campbell.com

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  staticAssets:
    enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: true
    enabled: true
    extraTls:
      - secretName: home-server-wildcard

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
