configs:
  secret:
    argocdServerAdminPassword: "$2a$10$3oZjPu9AFz33sKQ3LsQ9UuquA6RttoURjs6CXRCFazevdydHaa0ba"
  cm:
    kustomize.buildOptions: "--enable-helm"

server:
  staticAssets:
    enabled: true
  ingress:
    enabled: true
    hostname: home-server
    path: "/argocd(/|$)(.*)"
    pathType: ImplementationSpecific
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  extraArgs:
    - --insecure
    - --basehref
    - /argocd
