apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

helmCharts:
  - name: postgresql
    repo:  https://charts.bitnami.com/bitnami
    version: 14.0.1
    valuesFile: values.yaml
    releaseName: main
    namespace: postgres
    includeCRDs: true

resources:
  - secrets.yaml
