apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-camunda-worker
  labels:
    app: ktor-camunda-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-camunda-worker
  template:
    metadata:
      labels:
        app: ktor-camunda-worker
    spec:
      containers:
        - name: web
          image: ghcr.io/antoinecampbell/ktor-worker:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          env:
            - name: ZEEBE_GRPC_ADDRESS
              value: http://camunda-platform-zeebe-gateway.camunda-platform.svc.cluster.local:26500
            - name: ZEEBE_REST_ADDRESS
              value: http://camunda-platform-zeebe-gateway.camunda-platform.svc.cluster.local:8080
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ktor-camunda-worker
  labels:
    app: ktor-camunda-worker
spec:
  selector:
    app: ktor-camunda-worker
  ports:
    - port: 8080
      targetPort: http
      name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ktor-camunda-worker
  name: ktor-camunda-worker
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: ktor-camunda-worker
