apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - app.yaml

images:
  - name: app
    newName: ghcr.io/antoinecampbell/ktor-camunda-worker
    newTag: 1.0.0
