apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-platform

helmCharts:
  - name: camunda-platform
    repo:  https://helm.camunda.io
    version: 8.1.3
    valuesFile: values.yaml
    releaseName: camunda-platform
    namespace: camunda-platform
    includeCRDs: true
