apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-platform

configMapGenerator:
  - name: zeebe-grafana-dashboard
    files:
      - grafana-dashboards/zeebe.json
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      labels:
        grafana_dashboard: "1"
  - name: zeebe-overview-grafana-dashboard
    files:
      - grafana-dashboards/zeebe-overview.json
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      labels:
        grafana_dashboard: "1"

helmCharts:
  - name: camunda-platform
    repo: https://helm.camunda.io
    version: 10.6.0
    valuesFile: values.yaml
    releaseName: camunda-platform
    namespace: camunda-platform
    includeCRDs: true
