apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-platform

helmCharts:
  - name: camunda-platform
    repo: https://helm.camunda.io
    version: 10.4.2
    valuesFile: values.yaml
    releaseName: camunda-platform
    namespace: camunda-platform
    includeCRDs: true
