global:
  identity:
    auth:
      enabled: false
  elasticsearch:
    host: main-es-internal-http.elastic.svc.cluster.local

identity:
  enabled: false
  firstUser:
    username: admin
    firstName: admin
    existingSecret: camunda-platform-secrets

optimize:
  enabled: false

zeebe-gateway:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

zeebe:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

operate:
  contextPath: /operate
  ingress:
    enabled: true
    host: home-server
    path: /operate
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity: {}

tasklist:
  enabled: false
  contextPath: /tasklist
  ingress:
    enabled: true
    host: home-server
    path: /tasklist
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

elasticsearch:
  enabled: false

connectors:
  enabled: false

webModeler:
  enabled: false
