global:
  identity:
    auth:
      enabled: false
  elasticsearch:
    url:
      host: main-es-internal-http.elastic.svc.cluster.local

identityKeycloak:
  enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebeGateway:
  contextPath: /zeebe-gateway-rest
  ingress:
    grpc:
      enabled: true
      path: /zeebe-gateway-grpc
      host: home-server
    rest:
      enabled: true
      path: /zeebe-gateway-rest
      host: home-server
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

zeebe:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistenceType: disk
  pvcSize: 10Gi
  pvcStorageClassName: microk8s-hostpath
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []
  retention:
    enabled: true
    minimumAge: 7d

operate:
  contextPath: /operate
  ingress:
    enabled: true
    host: home-server
    path: /operate
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity: {}
  retention:
    enabled: true
    minimumAge: 7d

tasklist:
  enabled: false
  contextPath: /tasklist
  ingress:
    enabled: true
    host: home-server
    path: /tasklist
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []
  retention:
    enabled: true
    minimumAge: 7d

prometheusServiceMonitor:
  enabled: true

elasticsearch:
  enabled: false

connectors:
  enabled: false

webModeler:
  enabled: false
