global:
  identity:
    auth:
      enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebe-gateway:
  replicas: 1
  service:
    type: NodePort
  resources:
    requests:
      cpu: 250m
  affinity: {}

zeebe:
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 250m
      memory: 512Mi
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity: {}

operate:
  contextPath: /operate
  ingress:
    enabled: true
    host: home-server
    path: /operate
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity: {}

tasklist:
  enabled: false
  contextPath: /tasklist
  ingress:
    enabled: true
    host: home-server
    path: /tasklist
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity: {}

elasticsearch:
  config:
    discovery:
      type: single-node
  master:
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 500m
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
  persistence:
    enabled: false
  antiAffinity: soft
  nodeAffinity: {}

connectors:
  enabled: false
