global:
  identity:
    auth:
      enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebe-gateway:
  replicas: 1
  resources:
    requests:
      cpu: 250m
  affinity: {}

zeebe:
  resources:
    requests:
      cpu: 250m
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity: {}

operate:
  env:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: /operate
  ingress:
    enabled: true
    className: public
    path: /operate
  resources:
    requests:
      cpu: 250m
  affinity: {}

tasklist:
  env:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: /tasklist
  ingress:
    enabled: true
    className: public
    path: /tasklist
  resources:
    requests:
      cpu: 250m
  affinity: {}

elasticsearch:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
  persistence:
    enabled: false
  antiAffinity: soft
  nodeAffinity: {}
