global:
  identity:
    auth:
      enabled: false
  elasticsearch:
    url:
      host: main-es-internal-http.elastic.svc.cluster.local

identityKeycloak:
  enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebeGateway:
  ingress:
    grpc:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: false
        nginx.ingress.kubernetes.io/backend-protocol: GRPC
        nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/24,10.8.0.0/24"
      enabled: true
      host: zeebe-gateway.home.antoine-campbell.com
      tls:
        enabled: true
        secretName: zeebe-tls
    rest:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: true
        nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/24,10.8.0.0/24"
      enabled: true
      host: zeebe-gateway-rest.home.antoine-campbell.com
      tls:
        enabled: true
        secretName: zeebe-tls
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: [ ]

zeebe:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 2Gi
  persistenceType: disk
  pvcSize: 10Gi
  pvcStorageClassName: microk8s-hostpath
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: [ ]
  retention:
    enabled: true
    minimumAge: 7d

operate:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: true
    enabled: true
    host: operate.home-server.antoine-campbell.com
    tls:
      enabled: true
      secretName: home-server-wildcard
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity: { }
  retention:
    enabled: true
    minimumAge: 7d

tasklist:
  enabled: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: true
    enabled: true
    host: tasklist.home-server.antoine-campbell.com
    tls:
      enabled: true
      secretName: home-server-wildcard
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: [ ]
  retention:
    enabled: true
    minimumAge: 7d

prometheusServiceMonitor:
  enabled: true

elasticsearch:
  enabled: false

connectors:
  enabled: false

webModeler:
  enabled: false
