global:
  identity:
    auth:
      enabled: false
ingress:
  enabled: true
  path: /camunda-platform
identity:
  enabled: false
zeebe:
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
elasticsearch:
  replicas: 1
