global:
  identity:
    auth:
      enabled: false

identity:
  enabled: false

optimize:
  enabled: false

zeebe-gateway:
  replicas: 1
  service:
    type: NodePort
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 450Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

zeebe:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

operate:
  contextPath: /operate
  ingress:
    enabled: true
    host: home-server
    path: /operate
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity: {}

tasklist:
  enabled: false
  contextPath: /tasklist
  ingress:
    enabled: true
    host: home-server
    path: /tasklist
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: []

elasticsearch:
  master:
    materOnly: true
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1500Mi
    persistence:
      enabled: false
      size: 4Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    enabled: false
  nodeAffinityPreset: soft
  podAffinityPreset: soft
  antiAffinity: soft
  nodeAffinity: {}

connectors:
  enabled: false

webModeler:
  enabled: false
