global:
  identity:
    auth:
      enabled: false
ingress:
  enabled: true
  path: /camunda-platform
identity:
  enabled: false
zeebe-gateway:
  replicas: 1
  resources:
    requests:
      cpu: 250m
  affinity: {}
zeebe:
  resources:
    requests:
      cpu: 250m
  persistenceType: local
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  affinity: {}
operate:
  resources:
    requests:
      cpu: 250m
  affinity: {}
tasklist:
  resources:
    requests:
      cpu: 250m
  affinity: {}
elasticsearch:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
  persistence:
    enabled: false
  volumeClaimTemplate:
    resources:
      requests:
        storage: 8Gi
  antiAffinity: soft
  nodeAffinity: {}
