apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
  - namespace.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 4.10.9
    valuesFile: values.yaml
    releaseName: argo-cd
    namespace: argo-cd
    includeCRDs: true