configs:
  secret:
    argocdServerAdminPassword: "$2a$10$fHShpyOkQGZQNTtmzu7Gl.3jSSnWOVIRT1.UHcXsBag8.25cfGG7q"

server:
  staticAssets:
    enabled: true
  config:
    kustomize.buildOptions: --enable-helm
  ingress:
    enabled: true
    paths:
      - /argocd(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  extraArgs:
    - --insecure
    - --basehref
    - /argocd