---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-encryption
spec:
  encryptedData:
    db-encryption-key: AgBHGJox7nqccZXnqM5SeTcpikTyIc1E++Tb9Qvt5jpt0v6ckX05fwrXVpVWtSGHUZFVpTMTkK7RglhURF0KLJrj4gsYG68biV9dterLhzKuE3fu8vM5zf5w60m9iCozVkHcZNIUgjH2RAgbL2nmaOihMtITqZKIfrUqD0mfXJL3w2ipuTOs5DOk7SkkqpUKffySlL7i0GCI1SKAX35zNKzpFPZEHvTN8lfujwzgI+0VAmmNSaeSviVsenX9sxLXD4HnFHuDYvQT5iNANUb6cTgEZlqwV4BlPcEf3AioNduO95Ywv3XpKBEH8ivMiaxvwoRdWRI9c9p0mvSNFDUQzHv7FNQpB4iyQGb1Trl8e4rb8I6luIPEqHIrQxpuan0U6eoM4Wmwi7qQHr150DAHQrgELJAzxn3ree8vUOuulTIWHbZ9zRPkirm2TfswpmclV45pHt62+kDGac/Dn/pv6fcrL7hxsugAU+iWV4efAmqpEaAJetaaOKW5dSj/Q4mIuLwau1GDEwU7iBlKH5TAG+1+9M7xXLuMxnI/mM2LlNg7JUWUZZALVu1RmTo8lulm8c5/C4b8ucHAUKjxSlhNKXHHfsp1uv6dbryR3mxEqIEQn9hSQ5Vmb4GNgKeTfacOWZAi0sBGJW9zNiA8sPijkMIYf5J/4kqxI5kJZS83pvEWKULPMm5gI9zo/4xZYIK3uEBOsOKez2fhXz5gRIzy1aIXnEFxl5Rcs0VVJavy+/9Sa6ASqsy3H/ZIFo17Xgj0IcRjUhpKbu63D5+igMHaXiMn
  template:
    metadata:
      name: db-encryption
      namespace: homarr
