env:
  TZ: America/New_York
ingress:
  enabled: true
  hosts:
  - host: home-server.antoine-campbell.com
    paths:
      - path: /
  tls:
    - secretName: home-server-wildcard-signed-prod
envSecrets:
  dbEncryption:
    existingSecret: db-encryption
    key: db-encryption-key
persistence:
  homarrDatabase:
    enabled: true
    volumeClaimName: homarr-database
    storageClassName: microk8s-hostpath
resources:
  limits:
    memory: 1Gi
