---
apiVersion: batch/v1
kind: Job
metadata:
  name: python-job
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: python-job
    spec:
      restartPolicy: Never
      containers:
        - name: python-job
          image: local/python-job
          imagePullPolicy: IfNotPresent
