apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reflector

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 7.1.262
    releaseName: reflector
    namespace: reflector
    includeCRDs: true
    valuesFile: values.yaml
